# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d4f507b03ed800230507ee168cd8bf895f97bd8a26a440cfe541b06b064a21869692a5463be935f616045e7ce22f613c25e3c42a327ee76849d9359c449116e

test:
  secret_key_base: b869523f888a6ac6f268eb4e03e8a1d9182b53169874925ce87219232f072fa7eeb331cf3563dc9b2a51b6db6ec5594f7e761df2763469c36fb945804837c6e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
